#!/usr/bin/env bash
#
# Also graciously borrowed from @holman's dotfiles repo.
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done